version: "3.8"

volumes:
  staticfiles:
  dbdata:
  celerybeatdata:
  backend-code:
  mediafiles:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    container_name: django-backend
    command: >
      sh -c "./wait-for-db.sh db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py create_admin &&
             python manage.py collectstatic --noinput &&
             chmod 777 /app/staticfiles/admin &&
             uvicorn ft_transcendance.asgi:application --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DJANGO_SETTINGS_MODULE=ft_transcendance.settings
    ports:
      - "8000:8000"
    volumes:
      - backend-code:/app
      - staticfiles:/app/staticfiles
      - mediafiles:/app/media
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx-server
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/media
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ft_transcendence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: HK@12345@42Student
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6380:6379"
    restart: always

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    container_name: celery-worker
    command: celery -A ft_transcendance worker --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=ft_transcendance.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - backend
    env_file:
      - .env
    restart: always

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    container_name: celery-beat
    command: >
      sh -c "./wait-for-db.sh db &&
             python manage.py setup_celery_beat &&
             celery -A ft_transcendance beat --loglevel=info --schedule=/app/data/celerybeat-schedule"
    environment:
      - DJANGO_SETTINGS_MODULE=ft_transcendance.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - backend
    env_file:
      - .env
    volumes:
      - celerybeatdata:/app/data
    restart: always
