services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=ft_transcendence
      - DB_USER=postgres
      - DB_PASSWORD=HK@12345@42Student
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres
    environment:
      - POSTGRES_DB=ft_transcendence
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=HK@12345@42Student
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
