services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=ft_transcendance.settings
    depends_on:
      - db
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl/server.crt:/etc/ssl/server.crt:ro
      - ./nginx/ssl/server.key:/etc/ssl/server.key:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: ft_transcendance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /goinfre/postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery-worker
    command: celery -A ft_transcendance worker --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=ft_transcendance.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - backend
    restart: always

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery-beat
    command: >
      sh -c "python manage.py setup_celery_beat &&
           celery -A ft_transcendance beat --loglevel=info --schedule=/app/data/celerybeat-schedule"
    environment:
      - DJANGO_SETTINGS_MODULE=ft_transcendance.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - backend
    volumes:
      - /goinfre/celery-beat-data:/app/data
    restart: always
