# Generated by Django 4.2.16 on 2024-12-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='default_session_id', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('game_mode', models.CharField(default='local', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.PositiveIntegerField(default=0)),
                ('player2_score', models.PositiveIntegerField(default=0)),
                ('forfeit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_duration', models.FloatField(default=0, help_text='Duration of the match in seconds')),
                ('total_ball_hits', models.PositiveIntegerField(default=0)),
                ('avg_ball_speed', models.FloatField(blank=True, null=True)),
                ('max_ball_speed', models.FloatField(blank=True, null=True)),
                ('longest_rally', models.PositiveIntegerField(default=0)),
                ('reaction_time_player1', models.FloatField(blank=True, null=True)),
                ('reaction_time_player2', models.FloatField(blank=True, null=True)),
                ('victory_margin', models.PositiveIntegerField(blank=True, null=True)),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_history', to='game.gamesession')),
            ],
        ),
    ]
