# Generated by Django 4.2.16 on 2024-12-18 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_matchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhistory',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='points_conceded_by_loser',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='points_scored_by_winner',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='winner',
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='player1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player1_match_history', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='player2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player2_match_history', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
