# Generated by Django 4.2.16 on 2024-12-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_matchhistory_loser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='forget',
            field=models.BooleanField(default=False),
        ),
    ]
