# Generated by Django 4.2.16 on 2024-12-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_matchhistory_forget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchhistory',
            old_name='forget',
            new_name='forfeit',
        ),
    ]
