# Generated by Django 4.2.16 on 2024-12-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rename_forget_matchhistory_forfeit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='game_mode',
            field=models.CharField(default='local', max_length=50),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='avg_ball_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='longest_rally',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='match_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='max_ball_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='player1_missed_hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='player2_missed_hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='reaction_time_player1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='reaction_time_player2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='total_ball_hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='turning_point_score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='victory_margin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
