# Generated by Django 4.2.16 on 2024-12-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gamesession_game_mode_matchhistory_avg_ball_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='match_duration',
            field=models.FloatField(default=0, help_text='Duration of the match in seconds'),
        ),
    ]
