# Generated by Django 4.2.16 on 2024-12-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_matchhistory_match_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchhistory',
            name='player1_missed_hits',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='player2_missed_hits',
        ),
        migrations.RemoveField(
            model_name='matchhistory',
            name='turning_point_score',
        ),
    ]
