# Generated by Django 4.2.16 on 2024-11-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_feedupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedupdate',
            name='user',
            field=models.TextField(),
        ),
    ]
