# Generated by Django 4.2.16 on 2024-11-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_transcendenceuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcendenceuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
