# Generated by Django 4.2.16 on 2024-12-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_transcendenceuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcendenceuser',
            name='code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcendenceuser',
            name='two_factor_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
