# Generated by Django 4.2.16 on 2024-11-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_feedupdate_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedupdate',
            options={'ordering': ['created_at']},
        ),
    ]
