# Generated by Django 4.2.16 on 2024-11-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_feedupdate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcendenceuser',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='transcendenceuser',
            name='wins',
        ),
    ]
